version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - sula-db:/var/lib/postgresql/data
  
  server:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '5000:5000'

volumes:
  sula-db: